name: SOMA
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - matplotlib
  - numpy
  - scipy
  - somoclu
  - tqdm
  - ipywidgets
  - astropy
  - pandas
  - joblib
  - scikit-learn
  - statsmodels
